name: Build

on:
  push:
    branches: [main]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Build
        run: cargo build --release
        env:
          CARGO_PROFILE_RELEASE_LTO: "false"
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: windows
          path: |
            target/release/pop_the_lock.exe
            assets/

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Install dependencies
        run: sudo apt-get install -y libasound2-dev libudev-dev libwayland-dev libxkbcommon-dev
      - name: Build
        run: cargo build --release
        env:
          CARGO_PROFILE_RELEASE_LTO: "false"
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: linux
          path: |
            target/release/pop_the_lock
            assets/